### PR TITLE
add uptime command back in

### LINKED ISSUE #11: Add back in !uptime command
The code stopped working when I was "improving" something else so I deleted it. But it's there in a commit somewhere

### PR DESCRIPTION
**Pull request by rugglcon**
Closes #11

### CODE REVIEW

**Comment by rugglcon** [comment]
Sorry for all the commits, I wanted to format the messages correctly.

**Comment by patomation** [comment]
Thanks for for making this happen. Did you find the old code that was removed?
One thing could you rebase the commits and flatten them into one?

**Comment by rugglcon** [comment]
Yes I was able to find the old code, but it looks like you've refactored a bit how the bot actually runs commands, so I was able to copy most of it back in but not all.

And absolutely I can rebase sometime today. Thanks for the review.

**Comment by patomation** [comment]
Eh, I just merged it haha. Thanks for digging around and making it work.

**Comment by patomation** [comment]
I thought I merged it. Hmmm

**Comment by patomation** [comment]
Ahh, All I did was fix a merge conflict when I merged in master. I shouldn't have done that. I did all that before I read your comment.

**Comment by patomation** [comment]
Sorry about the spammy messages, but I hope this reaches you in time @rugglcon. I figured out how to pull down a copy of this pull request. So i think I can handle flattening it and you should still get credit for it. I would also like to make some edits to the data file is read.

**Comment by rugglcon** [comment]
Hey no problem, I always do extra PRs just in case one doesn't get merged or count for some weird reason. 

Sorry I never replied, I was working at an early voting location then just got busy with life things, but thank you for merging it!

**Pull request merged**
