### PR TITLE
Update TODO.md

### PR DESCRIPTION
**Pull request by ChattrBox-Forum**
Added a new TODO

### CODE REVIEW

**Comment by patomation** [comment]
I like the idea of making an app that sets off an alarm for people traveling at a given speed.
However this is beyond the scope of a twitch chat bot overlay system. 
But I would like to see about making a speed alarm app on stream stream in the future.

**Comment by ChattrBox-Forum** [comment]
Not on the chat bot but as a seperate app

**Comment by ChattrBox-Forum** [comment]
I said it to be as a seperate website or web app. Why i gave this idea is this will be a really helpful project for people in India

**Comment by patomation** [comment]
We should try to make this app sometime.

**Pull request closed without merging**
