### PR TITLE
#21 add type checking webpack plugin to webpack configuraton

### PR DESCRIPTION
**Pull request by eLeontev**
**Issue:** #21 
**Reason:** eslit does not validate type checking issues
**Changes:** add type-checking webpack plugin to highlight if bundle has type errors

**Result:**
Screenshot 2020-10-18 at 15 55 04

p.s. it's known issues with eslint. To validate types you have two ways - add validation on build stage (this PR) or add one more script to run `tsc` separately to validate the types.

### CODE REVIEW

**Comment by patomation** [comment]
Looks good. I'll take a look at fork-ts-checker-webpack-plugin when npmjs isn't having server problems.

**Comment by patomation** [comment]
What about type checking node stuff like the backed that does not go though webpack?

**Comment by eLeontev** [comment]
as I mentioned above the second way with using `tsc` will cover all, but we need to update tsconfig to fix the issues related to types.

Anyway I added the script how it can be  `"lint:typeChecking": "tsc --noEmit"` 

For now it rises 9 errors which mostly can be fixed in tsconfig.
Screenshot 2020-10-19 at 10 28 07

**Comment by eLeontev** [comment]
@patomation hi, can we merge it or you have any other rquirements?

**Comment by patomation** [comment]
I have set this project up in a pipline: typescript to javascript to bundle ect.
tsc is run both on the bot/backend and overlay/client catching all the compile errors. Then webpack run off the transpiled js files. Webpack never sees a typescript file. In the documentation example for that ts hooks webpack plugin; they are using ts-loader; which we are not. So the plugin does nothing.

Having the tsconfig in the root is redundant since each concern in this project has a tsconfig file already. There is a config for bot, overlay and test.

What I was really hoping for is someone could figure out how to make typescript more strict and always require method arguments and returns to be typed weather they are being exported or not. I guess It's my fault for being to ambiguous in my issue. 
While I really appreciate your time and effort that was put into this pull request; I'm not sure if it's going to be something we merge into the source.

**Comment by eLeontev** [comment]
@patomation can you add accepted label to the PR to add my PR to hacktoberfest score? thanks!
Screenshot 2020-10-25 at 18 54 22

**Pull request closed without merging**
